### PR TITLE
Update Dev Dependencies, Add More Code Quality Tools

### PR DESCRIPTION
**Pull request by DavidTPate**
This PR updates an outdated dev dependency (`jscs`) and pulls in additional code quality tools adding `eslint` to the party and configuring `jscs`, `buddy.js`, and `jshint` a bit better.

### CODE REVIEW

**Comment by DavidTPate** [comment]
@RiptideElements/platform anyone have a chance to review?

**Comment by DavidTPate** [comment]
@RiptideElements/platform anyone have a chance to review?

**Comment by toaster33** [comment]
:+1:

**Comment by ahoran3** [comment]
All checks out to me :ok_hand:

**Pull request merged**
