### PR TITLE
Fix infinite loop listing large directories

### PR DESCRIPTION
**Pull request by slegdon**
The ListAllObjects and ListAllObjectsFiles functions pass the incorrect value to recursive calls to themselves when fetching directory listings that return more than 100 entries (the AWS default max returned entries).

I've corrected this and added some tests to prove they work in readdirp() and listContents().

As I work in a VPC environment, I had to change the tests so that I can use a session token for authorisation. Using the AWS api CredentialProviderChain should work for other ways of specifying credentials, but I can't test that. Happy for you to just cherry-pick the tests and leave authentication as-is if that suits the project better.

Simon

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/RiptideElements/s3fs/pull/138" target="_blank">ReviewNinja

**Comment by DavidTPate** [comment]
Thanks for the contribution! I confirmed what you described by taking a look at the [documentation](http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#listObjects-property). Glad that this is getting fixed and that you included some tests!

I'm going to go ahead and pull your commits into a branch for the repo and do a little bit of cleanup on them so we can get them run against our CI and then get that stuff merged and released.

**Comment by slegdon** [comment]
Awesome! I'll look out for the release version.

**Comment by DavidTPate** [comment]
Your changes were merged in with #139 and released with version `2.4.8` which just went out. Thanks for the contribution!

**Pull request closed without merging**
